services:
  registry:
    build:
      context: ./registry
      dockerfile: Dockerfile
    volumes:
      - registry-data:/var/lib/mysql

  archive:
    build:
      context: ./archive
      dockerfile: Dockerfile
    volumes:
      - archive-data:/data

  lakehouse:
    build:
      context: ./lakehouse
      dockerfile: Dockerfile
    volumes:
      - lakehouse-data:/data

  ingestor:
    build:
      context: ./ingestor
      dockerfile: Dockerfile
    depends_on:
      - lakehouse 

  transformer:
    build:
      context: ./transformer
      dockerfile: Dockerfile
    depends_on:
      - lakehouse 
      - archive
      - registry

volumes:
  archive-data:
  registry-data:
  lakehouse-data:
